DROP TABLE IF EXISTS CUSTOMER_DETAILS;
CREATE TABLE CUSTOMER_DETAILS (
  CUSTOMER_DETAILS_ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(50) NOT NULL,
  MOBILE_NUMBER varchar(20) NOT NULL,
  ADDRESS varchar(100) NOT NULL,
  EID varchar(20) NOT NULL,
  PRIMARY KEY (CUSTOMER_DETAILS_ID)
);
DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
  ACCOUNT_ID int(11) NOT NULL AUTO_INCREMENT,
  ACCOUNT_NAME varchar(100) NOT NULL,
  PRIMARY KEY (ACCOUNT_ID)
);
DROP TABLE IF EXISTS NETWORK_DETAILS;
CREATE TABLE NETWORK_DETAILS (
  NETWORK_DETAILS_ID int(11) NOT NULL AUTO_INCREMENT,
  NETWORK_TYPE varchar(100) NOT NULL,
  REGION_CODE varchar(100) NOT NULL,
  EMIRATE varchar(100) NOT NULL,
  BUILDING_NUMBER varchar(100) NOT NULL,
  BUILDING_NAME varchar(100) NOT NULL,
  LOCATION_STATUS varchar(100) NOT NULL,
  INSTALLATION_ADDRESS varchar(1000) NOT NULL,
  FDH_STATUS varchar(100) NOT NULL,
  ACCOUNT_ID int(11) NOT NULL,
  PRIMARY KEY (NETWORK_DETAILS_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID)
);
DROP TABLE IF EXISTS FLAT_DETAILS;
CREATE TABLE FLAT_DETAILS (
  FLAT_DETAILS_ID int(11) NOT NULL AUTO_INCREMENT,
  NETWORK_DETAILS_ID int(11) NOT NULL,
  FLAT_NO int(10) NOT NULL,
  ONT_REQUIRED_FLAG varchar(100) NOT NULL,
  ONT_TYPE varchar(100) NOT NULL,
  ONT_SERIAL_NO varchar(100) NOT NULL,
  MDF_CODE varchar(100) NOT NULL,
  PRIMARY KEY (FLAT_DETAILS_ID),
  FOREIGN KEY (NETWORK_DETAILS_ID) REFERENCES NETWORK_DETAILS (NETWORK_DETAILS_ID)
);
DROP TABLE IF EXISTS TRANSACTION_BACKEND_LOGGER;
CREATE TABLE TRANSACTION_BACKEND_LOGGER (
  ID int(10) NOT NULL AUTO_INCREMENT,
  SERVICE_ORDER varchar(100) DEFAULT NULL,
  TRANSACTION_ID varchar(20) NOT NULL,
  SERVICE_INTERFACE varchar(100) DEFAULT NULL,
  SERVICE_OPERATION varchar(100) DEFAULT NULL,
  RESPONSE_CODE varchar(10) NOT NULL,
  RESPONSE_DESCRIPTION varchar(100) NOT NULL,
  CHANNEL varchar(100) DEFAULT NULL,
  REQUEST varchar(1000) NOT NULL,
  RESPONSE mediumtext NOT NULL,
  REQUEST_TIME_IN date NOT NULL,
  RESPONSE_TIME_OUT date NOT NULL,
  PRIMARY KEY (ID)
);
DROP TABLE IF EXISTS TRANSACTION_LOGGER;
CREATE TABLE TRANSACTION_LOGGER (
  ID int(11) NOT NULL AUTO_INCREMENT,
  TRANSACTION_ID varchar(1000) NOT NULL,
  SERVICE_NAME varchar(1000) NOT NULL,
  CHANNEL varchar(1000) DEFAULT NULL,
  REQUEST_PAYLOAD varchar(1000) NOT NULL,
  RESPONSE_PAYLOAD varchar(10000) NOT NULL,
  REQUEST_TIME_IN date NOT NULL,
  RESPONSE_TIME_OUT date NOT NULL,
  CUSTOMER_IP varchar(10) DEFAULT NULL,
  EXCEPTION_STACK_TRACE varchar(1000) DEFAULT NULL,
  GUEST_SESSION varchar(100) DEFAULT NULL,
  MSISDN varchar(20) DEFAULT NULL,
  OPERATION varchar(50) NOT NULL,
  OS_VERSION varchar(10) DEFAULT NULL,
  USER_NAME varchar(20) DEFAULT NULL,
  STATUS varchar(20) DEFAULT NULL,
  SESSION_TOKEN varchar(100) DEFAULT NULL,
  PRIMARY KEY (ID)
);
